name: mlops-zoomcamp
channels:
  - conda-forge
  - bioconda
dependencies:
  - ca-certificates
  - hyperopt
  - ipykernel
  - jupyter
  - mlflow
  - numpy
  - openssl
  - pandas
  - pyarrow
  - python=3.12
  - scikit-learn
  - seaborn
  - snakemake
  - xgboost
