name: mlops-zoomcamp
channels:
  - conda-forge
  - bioconda
dependencies:
  - ca-certificates
  - hyperopt
  - ipykernel
  - jupyter
  - numpy
  - openssl
  - pandas
  - pyarrow
  - python==3.11.13
  - scikit-learn
  - seaborn
  - snakemake
  - xgboost
